server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: D:/Java/bookingApp/confsvr/src/main/resources/config/bookingservice